### ISSUE TITLE
SplitTimeslot help

### ISSUE THREAD

**Issue by DSp4wN** [TylerAHolden/react-schedule-meeting#38]
Hi, can you provide an example of split timeslot like if I want to have slots from 9am to 1pm and then from 3pm to 6pm with 1pm to 3pm removed from it? I tried to follow the documentation but I am having a hard time to get it to work.

**Comment by TylerAHolden** [comment]
You would pass in an array of those timeslots you mentioned into the availableTimeslots prop. The schema of that array object should be like: 
```jsx
type AvailableTimeslot = {
  startTime: Date;
  endTime: Date;
  id?: string | number | undefined;
};
```
So for you're specific example you would pass in something like: 

```jsx
<ScheduleMeeting
  borderRadius={10}
  primaryColor="#3f5b85"
  eventDurationInMinutes={30}
  availableTimeslots={[
  {
    startTime: new Date('2022-07-11 9:00'),
    endTime: new Date('2022-07-11 13:00')
  },
  {
    startTime: new Date('2022-07-11 15:00'),
    endTime: new Date('2022-07-11 18:00')
  },
]}
  onStartTimeSelect={console.log}
/>
```
