### ISSUE TITLE
Update react to react v17 

### ISSUE THREAD

**Issue by domgaulton** [TylerAHolden/react-schedule-meeting#46]
I would like to use it on a project using react 17 please

<img width="601" alt="Screenshot 2022-09-02 at 09 10 06" src="https://user-images.githubusercontent.com/8589283/188095148-91d6ff44-3ffd-4fe4-bbb4-ce807498bd98.png">

**Comment by TylerAHolden** [comment]
https://github.com/TylerAHolden/react-schedule-meeting/commit/f9b9f50a2872967b52fcc0f2d0a3d8f69f24efdc
