### ISSUE TITLE
Internationalization options

### ISSUE THREAD

**Issue by jrnkng** [TylerAHolden/react-schedule-meeting#48]
Hi, I have taken a look at the component you have created and I think it's terrific. One question: what is the support status of internationalization? (No AM/PM for times and months named according to a different language).

**Comment by TylerAHolden** [comment]
Are you looking for the format props? https://react-schedule-meeting.netlify.app/docs/all-props With those you can set the format string for date-fns.

**Comment by DorianMas** [comment]
Hi, thanks for this amazing tool! 
Would it be possible to show an example of how you can change the language of the date/time format? I tried according to date-fns documentation but without success...

**Comment by DorianMas** [comment]
It's working perfectly, thanks a lot!

**Comment by TylerAHolden** [comment]
Awesome! let me know if there is anything else we can improve!
