### ISSUE TITLE
Clear selected time slot after selection - suggestion 

### ISSUE THREAD

**Issue by sergeyd63** [TylerAHolden/react-schedule-meeting#51]
Hey, cool component 👍

Wanted to see if you guys can add clearing of the selected time slot after clicking `Confirm`
Maybe even do it conditional, like return boolean from `onStartTimeSelect` and if it's `true` clear the selection - `setSelectedItemIndex(-1)`. Or clear it always 🤷‍♀️. 
Could be useful... At least in my case

Thanks

**Comment by TylerAHolden** [comment]
I guess the UI's assumption is that once you click confirm, the schedule component would be taken away or hidden. I suppose i can see a case for where you might want to keep it but it wouldn't be practical UX to keep the schedule component visible with nothing selected even though the external state would have a time selected - In that scenario it would be better if the schedule actually showed the time selected maybe without the "confirm" text but even still, wouldn't it be better to display a completely alternative UI component showing that something has been selected?

Can you show me your use-case where the schedule needs to remain visible with a time slot already selected? I'm not understanding what the benefit would be

**Comment by TylerAHolden** [comment]
Unless, are you using the schedule component to register multiple time slot selections?

**Comment by sergeyd63** [comment]
I was thinking about use case like you have when scheduling a job interview, when you asked to select multiple optional time slots. 
Right now, i'm using only 1, so i can hide the component after selection. I'm actually updating the time slots after selection by removing the selected slot, and it creates a case where there is another slot (next one) is selected on the screen.
But i want to give an option of multi selection

If it makes sense 😀

And thanks for a quick reply

**Comment by TylerAHolden** [comment]
Gotcha yea I can add a way to unset the "confirm" state

**Comment by sergeyd63** [comment]
cool. thanks

**Comment by TylerAHolden** [comment]
Okay its available in 0.4.0 [Commit](https://github.com/TylerAHolden/react-schedule-meeting/commit/88fe0d5389ad4ae446670f8b6552de3eec567fd1) 
Here's an example: [Example & Usage](https://react-schedule-meeting.netlify.app/docs/examples/#resetting-state-after-a-start-time-is-selected)
