### ISSUE TITLE
(Suggestion) Highlight selected timeslot

### ISSUE THREAD

**Issue by arildsela93** [TylerAHolden/react-schedule-meeting#53]
I would suggest that there should be a way to highlight the selected timeslot, to increase user experience.
Maybe there is a way to do that, but I couldn't find

**Comment by TylerAHolden** [comment]
Okay i just published a new major version 1.2.0 which includes an internal state for the selected start time and a selectedStartTime Date prop if you want to override the internal state especially for displaying a pre-existing selection on mount.
