### ISSUE TITLE
update React to React 18.0.0

### ISSUE THREAD

**Issue by DelicaTessa** [TylerAHolden/react-schedule-meeting#56]
I tried to use this in a project but I use React v18.0.0.
<img width="493" alt="Scherm­afbeelding 2022-11-22 om 14 17 17" src="https://user-images.githubusercontent.com/58122045/203323636-1a5b3719-90aa-4d33-962a-03b7fd50390f.png">

**Comment by TylerAHolden** [comment]
I haven't checked on compatibility for react 18 but I can test sometime this week. Do you have styled-components added as a dependency?

**Comment by DelicaTessa** [comment]
> 

Yes I do :  "styled-components": "^5.3.6",

**Comment by TylerAHolden** [comment]
I'm not able to reproduce this with react 18. Can you share a test repo with the issue present?

**Comment by TylerAHolden** [comment]
Upgraded peer dependencies to react 18 in 3.0.0
