### ISSUE TITLE
Incorrect days availability if startTime and endTime hava few days in difference

### ISSUE THREAD

**Issue by AlexanderKapelyukhovskiy** [TylerAHolden/react-schedule-meeting#72]
I'm using version `4.2.0` of the react-schedule-meeting component and encountering an issue with days availability when setting `startTime` and `endTime` with a few days in difference. Specifically, if I set `startTime` as `02.18.2024T00:00:00.000` and `endTime` as `02.22.2024T00:00:00.000`, the `ScheduleMeeting` component only shows available days for `02.18.2024` and `02.22.2024`. Days in between (19th, 20th, and 21st of February) are marked as unavailable. Additionally, clicking on 02.22.2024 reveals no available slots.

Expected Behavior:
I expect the `ScheduleMeeting` component to display available days for 18th, 19th, 20th, and 21st of February, and exclude 22nd of January from being highlighted as available.

Impact:
This issue is critical for our workflow as it prevents us from utilizing the `ScheduleMeeting` component as intended, impacting user experience and scheduling functionality.

Reproduction Steps:

Set `startTime` as `02.18.2024T00:00:00.000` and `endTime` as `02.22.2024T00:00:00.000`.
Observe the displayed availability of days in the `ScheduleMeeting` component.
Workaround:
As a temporary workaround, we've implemented a transformation of the available time model to include extra intervals for days in between. However, this solution is not ideal and we seek a resolution from the maintainers.

This issue is critical for our use case, and we kindly request prompt attention and resolution from the maintainers.

**Comment by TylerAHolden** [comment]
Okay Alexander prompt attention and resolution will be on the top of my after-work priority list for the day, just for you. You'd be expecting timeslots to show up essentially 24hrs per day?

**Comment by AlexanderKapelyukhovskiy** [comment]
Dear Tyler,

Thank you for your prompt attention to this matter.

Yes, you understand correctly. I expect to have timeslots available throughout all days between the `startTime` and `endTime` parameters.

In the example I provided, where there are days in between such as the 19th, 20th, and 21st of February, I anticipate having 24 timeslots available per day, assuming an `eventDurationInMinutes = 60`.

Your assistance in resolving this issue is greatly appreciated.

**Comment by TylerAHolden** [comment]
4.2.1 should resolve this issue and it has just been published. You can see the commit changes here: https://github.com/TylerAHolden/react-schedule-meeting/commit/41ba0e4d55cc061b2a0cccce2598e0af354cc2be

Let me know if that doesn't work for you.

**Comment by AlexanderKapelyukhovskiy** [comment]
Dear Tyler,

Thank you for your prompt attention and assistance in resolving the main issue. Your efforts are greatly appreciated.

While the main issue has been resolved and I can now see available slots in between, I've noticed a minor issue that I previously described.

Specifically, when I pass the time range from 2/15/2024T0:00:00.000 to 2/18/2024T0:00:00.000, I expect to see the dates 15th through 17th of February highlighted as available, with the 18th of February not highlighted as available. However, currently, the 18th of February is shown as available, and upon clicking it, it displays "No times available".

Your attention to this matter is greatly appreciated.
![image](https://github.com/TylerAHolden/react-schedule-meeting/assets/849013/90242b73-b3d0-49da-83e7-ec0b8ac5edf9)

**Comment by TylerAHolden** [comment]
Alright Alexander, check out 4.2.2 just released - should be good this time.

**Comment by AlexanderKapelyukhovskiy** [comment]
Tyler,

Thank you so much for your swift action and for releasing version 4.2.2! I truly appreciate your dedication and commitment to addressing the issue promptly. I'll be sure to check out the latest release and provide feedback if needed. Your assistance is greatly valued.
