### ISSUE TITLE
Incorrect Next Available Date Message in Available Timeslots Section

### ISSUE THREAD

**Issue by AlexanderKapelyukhovskiy** [TylerAHolden/react-schedule-meeting#74]
Hello Tyler,

Thank you for your prompt support with the issues I discovered previously. However, I've come across a new issue that I believe may be related to Issue #72.

When we have multiple-day intervals, the component displays an incorrect 'Next Available Day' message in the available slots section. I've attached a screenshot below to illustrate the problem.
![image](https://github.com/TylerAHolden/react-schedule-meeting/assets/849013/9d6f60de-57ee-475d-b464-6b8974a2fc0c)

Could you please look into this?

Thank you.

**Comment by AlexanderKapelyukhovskiy** [comment]
Upon further investigation, it seems that the issue may be linked to the specific dates we're passing as the startDate and endDate parameters. We're currently using 02/21/2024 as the startDate and 02/26/2024 as the endDate.

Given our previous discussions regarding Issue #72, where we encountered challenges with date availability, I believe this context could help in identifying the root cause of the problem.

Thank you for your attention to this matter.

**Comment by TylerAHolden** [comment]
I just released 4.2.3 with a patch for a couple of different scenarios that it would have been showing the incorrect next date. Thanks for finding these issues. Let me know if that doesn't resolve the issue.

**Comment by AlexanderKapelyukhovskiy** [comment]
Tyler,

Thank you so much for your swift response and for addressing the issues promptly. I've just seen the release of version 4.2.3 and the patch you applied for the various scenarios that were causing incorrect next dates. Your dedication to resolving these issues is truly commendable.

I'll be sure to test out the fix shortly, and I'll definitely let you know if anything comes up.

Thanks again for your support and for continuously improving the project.
